"""Regenerate index/cards.json and index/INDEX.md from all records."""
from __future__ import annotations

import json
from datetime import date

from kblib import (DOMAINS, PENDING_DIR, ROOT, first_section_paragraphs,
                   iter_cards, utf8_stdout)


def main() -> None:
    utf8_stdout()
    cards = [card for card in iter_cards() if not card.parse_error]
    index = []
    for card in cards:
        meta = card.meta
        paragraphs = first_section_paragraphs(card.body)
        legacy_type = meta.get("type", "")
        entry_type = meta.get("entry_type") or (
            "literature" if legacy_type == "paper" else "legacy-note")
        primary_domain = meta.get("primary_domain") or meta.get("domain", "")
        domains = meta.get("domains") or ([primary_domain] if primary_domain else [])
        index.append({
            "slug": card.slug,
            "path": card.rel_path,
            "folder": card.folder,
            "title": meta.get("title", card.slug),
            "entry_type": entry_type,
            "publication_type": meta.get("publication_type", ""),
            "primary_domain": primary_domain,
            "domains": domains,
            "venue": meta.get("venue", ""),
            "doi": meta.get("doi", ""),
            "abstract": meta.get("abstract", ""),
            "status": meta.get("status", ""),
            "tags": meta.get("tags") or [],
            "authors": meta.get("authors") or [],
            "year": meta.get("year"),
            "citation_key": meta.get("citation_key", ""),
            "related": meta.get("related") or [],
            "drive": meta.get("drive") or [],
            "created": str(meta.get("created", "")),
            "rating": meta.get("rating"),
            "comments": meta.get("comments") or [],
            "uploaded_by": meta.get("uploaded_by", ""),
            "uploaded_at": str(meta.get("uploaded_at", "")),
            "summary": paragraphs[0] if paragraphs else "",
            "legacy_type": legacy_type,
        })
    index.sort(key=lambda item: (
        item["entry_type"] != "literature", item["primary_domain"], item["slug"]))

    out_dir = ROOT / "index"
    out_dir.mkdir(exist_ok=True)
    (out_dir / "cards.json").write_text(
        json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    literature_count = sum(item["entry_type"] == "literature" for item in index)
    lines = [
        "# Literature index",
        "",
        f"Auto-generated by `scripts/update_index.py` on {date.today()}; do not edit by hand.",
        f"Literature records: {literature_count}",
        "",
    ]
    for domain in DOMAINS:
        official = [
            item for item in index
            if item["entry_type"] == "literature"
            and item["primary_domain"] == domain
            and item["folder"] != PENDING_DIR
        ]
        if not official:
            continue
        lines += [f"## {domain}", ""]
        for item in official:
            year = f" ({item['year']})" if item["year"] else ""
            publication = item["publication_type"] or "unspecified"
            lines.append(f"- [{item['title']}]({item['path']}) - _{publication}_{year}")
        lines.append("")

    pending = [
        item for item in index
        if item["entry_type"] == "literature" and item["folder"] == PENDING_DIR
    ]
    if pending:
        lines += ["## Pending review", ""]
        for item in pending:
            lines.append(
                f"- [{item['title']}]({item['path']}) - "
                f"_{item['primary_domain']}_ `{item['status']}`")
        lines.append("")

    legacy = [item for item in index if item["entry_type"] == "legacy-note"]
    if legacy:
        lines += ["## Legacy notes", ""]
        for item in legacy:
            lines.append(
                f"- [{item['title']}]({item['path']}) - _{item['legacy_type']}_")
        lines.append("")

    (out_dir / "INDEX.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Indexed {len(index)} records -> index/cards.json, index/INDEX.md")


if __name__ == "__main__":
    main()
